### PR TITLE
StationName addition and RT fix

### PR DESCRIPTION
**Pull request by owenashurst**
Added rdsStationName to datastruct.h
Tweaked startup command to use rdsStationName as PS and songArtist and songName as RT.
Added stationName to settings_provider.cc

### CODE REVIEW

**Comment by morrolinux** [comment]
Looks alright to me. Have you tested it yet?

**Comment by owenashurst** [comment]
Yes I've tested it, seems to work fine.

**Comment by morrolinux** [comment]
Thanks for your contribution

**Comment by owenashurst** [comment]
You're welcome :)

**Pull request merged**
